# Generated by Django 6.0.7 on 2026-08-02 16:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mac_address', models.CharField(max_length=50, unique=True)),
                ('room_label', models.CharField(default='Unnamed device', max_length=100)),
                ('room_type', models.CharField(blank=True, choices=[('bedroom', 'Bedroom'), ('living_room', 'Living Room'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('office', 'Office'), ('server_room', 'Server Room'), ('other', 'Other')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('light', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.device')),
            ],
            options={
                'db_table': 'sensor_readings',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('temp_spike', 'Temperature Spike'), ('temp_drop', 'Temperature Drop'), ('humidity_jump', 'Humidity Jump'), ('humidity_drop', 'Humidity Drop'), ('light_spike', 'Light Spike'), ('sensor_flatline', 'Sensor Flatline'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='sensors.device')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='sensors.sensorreading')),
            ],
            options={
                'db_table': 'anomalies',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateField()),
                ('avg_temperature', models.FloatField(blank=True, null=True)),
                ('min_temperature', models.FloatField(blank=True, null=True)),
                ('max_temperature', models.FloatField(blank=True, null=True)),
                ('avg_humidity', models.FloatField(blank=True, null=True)),
                ('min_humidity', models.FloatField(blank=True, null=True)),
                ('max_humidity', models.FloatField(blank=True, null=True)),
                ('avg_light', models.FloatField(blank=True, null=True)),
                ('min_light', models.FloatField(blank=True, null=True)),
                ('max_light', models.FloatField(blank=True, null=True)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='sensors.device')),
            ],
            options={
                'db_table': 'daily_summary',
                'ordering': ['-summary_date'],
                'indexes': [models.Index(fields=['device', '-summary_date'], name='idx_summary_device_date')],
                'unique_together': {('device', 'summary_date')},
            },
        ),
        migrations.CreateModel(
            name='AiInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_text', models.TextField()),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='sensors.device')),
            ],
            options={
                'db_table': 'ai_insights',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['device', '-generated_at'], name='idx_insights_device_time')],
            },
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['device', '-recorded_at'], name='idx_readings_device_time'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['device', '-detected_at'], name='idx_anomalies_device_time'),
        ),
    ]
